"""
Auto-configure the backend .env file using the downloaded Firebase service account JSON.

The private key is stored as a single-line quoted string (required by .env format).

Usage:
    python setup_firebase.py
"""

import json
import os
import sys

# Ensure we can import the app even from this directory
sys.path.insert(0, os.path.dirname(__file__))

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))              # .../Projct/backend
PROJECT_ROOT = os.path.dirname(os.path.dirname(BASE_DIR))          # D:\Thesis Project
KEY_DIR = os.path.join(PROJECT_ROOT, "firebase private key")
ENV_PATH = os.path.join(BASE_DIR, ".env")


def main():
    # -- 1. Find the JSON key file ----------------------------------
    json_files = [f for f in os.listdir(KEY_DIR) if f.endswith(".json")]
    if not json_files:
        print(f"[ERROR] No JSON key file found in: {KEY_DIR}")
        print("   Make sure you placed the Firebase service account JSON there.")
        return 1

    key_path = os.path.join(KEY_DIR, json_files[0])
    print(f"[FOUND] {json_files[0]}")

    # -- 2. Read the service account JSON ---------------------------
    with open(key_path, "r") as f:
        creds = json.load(f)

    # -- 3. Build the .env content ----------------------------------
    private_key = creds.get("private_key", "")

    env_content = f"""# Firebase (auto-generated by setup_firebase.py)
FIREBASE_TYPE=service_account
FIREBASE_PROJECT_ID={creds.get("project_id", "")}
FIREBASE_PRIVATE_KEY_ID={creds.get("private_key_id", "")}
FIREBASE_PRIVATE_KEY="{private_key}"
FIREBASE_CLIENT_EMAIL={creds.get("client_email", "")}
FIREBASE_CLIENT_ID={creds.get("client_id", "")}
FIREBASE_AUTH_URI={creds.get("auth_uri", "https://accounts.google.com/o/oauth2/auth")}
FIREBASE_TOKEN_URI={creds.get("token_uri", "https://oauth2.googleapis.com/token")}
FIREBASE_AUTH_PROVIDER_CERT_URL={creds.get("auth_provider_x509_cert_url", "")}
FIREBASE_CLIENT_CERT_URL={creds.get("client_x509_cert_url", "")}

# Security
SECRET_KEY=your-secret-key-change-this-in-production
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# CORS
CORS_ORIGINS=http://localhost:5173,https://your-domain.com

# Environment
ENVIRONMENT=development
DEBUG=True
"""

    # -- 4. Write the .env file -------------------------------------
    with open(ENV_PATH, "w") as f:
        f.write(env_content)

    print("[OK] .env file written with Firebase credentials!")

    # -- 5. Test the connection -------------------------------------
    print("\nTesting Firebase connection...")
    try:
        # Force reload of settings after updating .env
        from dotenv import load_dotenv
        load_dotenv(ENV_PATH, override=True)

        from app.core.firebase import get_db, get_firebase_app
        # Clear any cached firebase app that may have used old credentials
        get_firebase_app.cache_clear()

        db = get_db()
        collections = list(db.collections())
        print("[OK] Firebase connected successfully!")
        print(f"   Project ID: {creds['project_id']}")
        print(f"   Collections: {len(collections)}")
        for c in collections:
            print(f"     - {c.id}")
        return 0

    except Exception as e:
        print(f"[FAIL] Connection failed: {e}")
        print("\n   Troubleshooting:")
        print("   1. Enable Firestore: Firebase Console > Build > Firestore > Create database")
        print("   2. Start Firestore in test mode (or set up proper rules)")
        print("   3. Make sure you have internet access")
        print("   4. Run: pip install -r requirements.txt")
        return 1


if __name__ == "__main__":
    sys.exit(main())
